pipeline {
    agent any

    tools {
        nodejs "nodejs"   // Jenkins లో NodeJS tool name
    }

    environment {
        SONAR_HOME = tool "sonar-scanner"
    }

    stages {

        stage('Git Checkout') {
            steps {
                git branch: 'main', 
                url: 'https://github.com/Bindupattem/choco-cream.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar-server') {
                    sh '''
                    $SONAR_HOME/bin/sonar-scanner \
                    -Dsonar.projectKey=choco-app \
                    -Dsonar.sources=. \
                    -Dsonar.host.url=http://<your-sonar-ip>:9000 \
                    -Dsonar.login=<your-token>
                    '''
                }
            }
        }

        stage('Run App') {
            steps {
                sh 'node server.js &'
            }
        }
    }
}
